name: eslint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.20.2'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
